name: Calculadora Secuencial y Paralela

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

  pruebas-paralelas:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        operacion: [sumar, restar]

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Ejecutar operacion ${{ matrix.operacion }}
        run: |
          echo "Creando script para operación..."
          echo "const calc = require('./calculadora'); console.log('Resultado de ${{ matrix.operacion }}:', calc.${{ matrix.operacion }}(5,2));" > test.js
          node test.js

  reporte-final:
    runs-on: ubuntu-latest
    needs: pruebas-paralelas
    steps:
      - name: Mostrar mensaje final
        run: echo "Todas las operaciones de la calculadora se ejecutaron correctamente"
   
  
