name: Calculadora Secuencial y Paralela
on:
 push: 
  branches: 
   -main

jobs:
   build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v5
       - name: Instalar Node.js
         run: |
           sudo apt-get update
           sudo apt-get install -y nodejs npm

   pruebas-paralelas:
    runs-on: ubuntu-latest
    needs: 
      build
    strategy:
       matrix:
          operacion: [sumas,restar]
    steps:
       - uses: actions/checkout@v5
       - name: Ejecutar operacion ${{matrix.operacion}}
         run: |
           echo "Creando script para operación..."
           echo "const calc= require('./calculadora'): console.log('Resultado de ${{matrix.operacion}}')":' calc.${{matrix.operacion}}(5,2));"
           node test.js

   reporte-final:
    runs-on: ubuntu-latest
    needs:
      pruebas-paralelas
    steps:
      - uses: actions/checkout@v5
      - name: Mostrar mensaje final
        run: echo "Todas las operaciones de la calculadora se ejecutaron correctamente"
      
   
   
  
