#No olvides crear la variable OPERACION en settings
name: Calculadora con Vars
on: 
  workflow_dispatch: 

jobs:
  calculadora-vars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Ejecutar operacion usando variable
        run: |
          echo "Creando archivo de prueba.."

          cat <<EOF > test.js
          const calc = require('./calculadora');
          console.log('Resultado de ' + process.env.OPERACION + ':', calc[process.env.OPERACION](10,5));
          EOF

          node test.js
        env:
          OPERACION: ${{ vars.OPERACION }}
